name: Build & Test
on: [push, pull_request]

jobs:  
  build_and_test:
    strategy:
      matrix:
        node: [8, 10, 12]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
        with:
          fetch-depth: 1
      - name: Setup node
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node }}
      - run: npm install -g yarn
      - run: yarn run build
      - run: yarn run lint
      - run: yarn run flow
      - run: yarn run test