name: Build Docs
on: [push, pull_request]
# TODO: only do this on changes to paths

jobs:
  docs:
    name: Build docs
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
        with:
          fetch-depth: 1
      - name: Setup node
        uses: actions/setup-node@v1
        with:
          node-version: 12
      - name: Build docs
        run: |
          cd website
          yarn install
          yarn run build
