name: Publish
on:
  push:
    branch: actions
    # paths:
    #   - website/
    #   - docs/

jobs:
  publish:
    name: Publish
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
        with:
          fetch-depth: 1
      - name: Setup node
        uses: actions/setup-node@v1
        with:
          node-version: 12
      - run: npm install -g yarn
      - run: cd website
      - run: yarn install
      - run: yarn run publish-gh-docs